version: "3"

services:
  p3db:
    image: postgres
    container_name: p3db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fullstack123
      - POSTGRES_DB=p3db
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: